name: OpenShift Enterprise by Red Hat
abbreviated_name: OpenShift
product_logo: portal.png
current_version: 2.2.0.GA
product_category: application-development
customer_portal_download_url: https://rhn.redhat.com/rhn/software/channel/downloads/Download.do?cid=21355
documentation_path: OpenShift_Enterprise
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKo9vXQ1Ywj5tfjCUsqyXBwq
vimeo_album: https://vimeo.com/album/3555893
skip_installation_instructions: true
skip_maven_instructions: true
skip_quickstart_link: true
buzz_tags:
  - openshift
  - openshiftv3
index:
  desc: |
    An open, hybrid Platform-as-a-Service (PaaS) that lets developers quickly develop, host, scale, and deliver apps in the cloud.
guides:
  Release_Notes:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html/2.2_Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html-single/2.2_Release_Notes/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/epub/2.2_Release_Notes/OpenShift_Enterprise-2-2.2_Release_Notes-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/pdf/2.2_Release_Notes/OpenShift_Enterprise-2-2.2_Release_Notes-en-US.pdf
  Administration_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html/Administration_Guide/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html-single/Administration_Guide/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/epub/Administration_Guide/OpenShift_Enterprise-2-Administration_Guide-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/pdf/Administration_Guide/OpenShift_Enterprise-2-Administration_Guide-en-US.pdf
  Cartridge_Specification_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html/Cartridge_Specification_Guide/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html-single/Cartridge_Specification_Guide/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/epub/Cartridge_Specification_Guide/OpenShift_Enterprise-2-Cartridge_Specification_Guide-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/pdf/Cartridge_Specification_Guide/OpenShift_Enterprise-2-Cartridge_Specification_Guide-en-US.pdf
  Client_Tools_Installation_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html/Client_Tools_Installation_Guide/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html-single/Client_Tools_Installation_Guide/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/epub/Client_Tools_Installation_Guide/OpenShift_Enterprise-2-Client_Tools_Installation_Guide-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/pdf/Client_Tools_Installation_Guide/OpenShift_Enterprise-2-Client_Tools_Installation_Guide-en-US.pdf
  Deployment_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html/Deployment_Guide/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html-single/Deployment_Guide/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/epub/Deployment_Guide/OpenShift_Enterprise-2-Deployment_Guide-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/pdf/Deployment_Guide/OpenShift_Enterprise-2-Deployment_Guide-en-US.pdf
  Puppet_Deployment_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html/Puppet_Deployment_Guide/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html-single/Puppet_Deployment_Guide/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/epub/Puppet_Deployment_Guide/OpenShift_Enterprise-2-Puppet_Deployment_Guide-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/pdf/Puppet_Deployment_Guide/OpenShift_Enterprise-2-Puppet_Deployment_Guide-en-US.pdf
  REST_API_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html/REST_API_Guide/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html-single/REST_API_Guide/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/epub/REST_API_Guide/OpenShift_Enterprise-2-REST_API_Guide-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/pdf/REST_API_Guide/OpenShift_Enterprise-2-REST_API_Guide-en-US.pdf
  Technical_Notes:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html/Technical_Notes/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html-single/Technical_Notes/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/epub/Technical_Notes/OpenShift_Enterprise-2-Technical_Notes-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/pdf/Technical_Notes/OpenShift_Enterprise-2-Technical_Notes-en-US.pdf
  Troubleshooting_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html/Troubleshooting_Guide/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html-single/Troubleshooting_Guide/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/epub/Troubleshooting_Guide/OpenShift_Enterprise-2-Troubleshooting_Guide-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/pdf/Troubleshooting_Guide/OpenShift_Enterprise-2-Troubleshooting_Guide-en-US.pdf
  User_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html/User_Guide/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html-single/User_Guide/index.html
      epub:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/epub/User_Guide/OpenShift_Enterprise-2-User_Guide-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/pdf/User_Guide/OpenShift_Enterprise-2-User_Guide-en-US.pdf
description: 'Develop, host, and scale your applications in the cloud.'

skip_maven_instructions: true
other_product: true
upstream_projects:
evaluation: https://access.redhat.com/products/openshift-enterprise-red-hat/evaluation
