name: Red Hat JBoss Enterprise Application Platform
abbreviated_name: JBoss EAP
product_logo: enterprise-app-platform.png
current_version: 6.4.0.CVE-2015-7501
# EAP is still using an old name for docs on the customer portal
documentation_path: JBoss_Enterprise_Application_Platform
product_category: application-development
xpaas_url: https://www.openshift.com/developers/jboss
intro_video: https://vimeo.com/95462201
vimeo_album: http://vimeo.com/album/2982375
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKpAr_6VUi6nkoSQDov8fuZg
index:
  desc: |
    Host your apps in an innovative, modular, cloud-ready architecture with powerful management, automation and developer productivity.
buzz_tags:
  - eap
  - jboss
  - jboss eap
guides:
  Release_Notes:
  Administration_and_Configuration_Guide:
  API_Documentation:
    formats:
      html:
      html-single:
  Development_Guide:
  Installation_Guide:
  Migration_Guide:
  Security_Guide:
  Getting_Started_Guide:
# EAP has an installer, we want to default to that
default_download_artifact_type: zip
description: 'An application platform for hosting your apps that provides an innovative modular, cloud-ready architecture, powerful management and automation, and world class developer productivity.'
upstream_projects:
  - wildfly
  - jgroups
  - hibernate
  - hornetq
  - jbossclustering
  - jbossmc
  - narayana
  - jbossweb
  - jbossws
  - ironjacamar
  - jgroups
  - mod_cluster
  - jbossas_osgi
  - jbosssso
  - picketlink
  - resteasy
  - weld
  - wise
  - xnio
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_eap.png
    title: HTML5 Mobile with EAP 6 at OpenShift
    text: Build HTML5 mobile applications with EAP 6
    url: /video/vimeo/92554627
evaluation: https://access.redhat.com/products/red-hat-jboss-enterprise-application-platform/evaluation
highlight_colour: \#0089D0
