name: Red Hat JBoss BPM Suite
abbreviated_name: JBoss BPM Suite
product_logo: bpm-suite.png
has_installer: true
current_version: 6.2.0.GA
documentation_minor_version: 6.2
product_category: application-development
xpaas_url: https://www.openshift.com/developers/jboss-bpms
intro_video: https://vimeo.com/142883902
vimeo_album: http://vimeo.com/album/2982446
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKphPQWLX8SPJlPyqDhpZS4U
skip_installation_instructions: true
skip_maven_instructions: true
index:
  desc: |
    A business process and decision management platform that combines business rules management, business process management (BPM), and complex event processing.
buzz_tags:
  - BPM Suite
  - jBPM
  - JBoss BPMS
guides:
  Release_Notes:
  Administration_And_Configuration_Guide:
  Business_Resource_Planner_Guide:
  Development_Guide:
  Getting_Started_Guide:
  Installation_Guide:
  Migration_Guide:
  User_Guide:
default_download_artifact_type: installer
description: 'A powerful combination of business rules management, business process management (BPM), and complex event processing.'
upstream_projects:
  - drools
  - guvnor
  - optaplanner
  - jbpm 
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_bpmsuite.png
    url: /quickstarts/brms/tasks-bpmsuite
evaluation: https://access.redhat.com/products/red-hat-jboss-bpm-suite/evaluation
