name: Red Hat JBoss Data Virtualization
abbreviated_name: JBoss Data Virtualization
product_logo: data-virtualization.png
current_version: 6.2.0.GA
product_category: application-development
documentation_minor_version: 6.2
xpaas_url: https://www.openshift.com/developers/jboss-data-virtualization
intro_video: https://vimeo.com/91533636
vimeo_album: http://vimeo.com/album/2982437
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKo6SigOgnSWYc6rhLemrDDS
skip_installation_instructions: true
skip_maven_instructions: true
index:
  desc: |
    A data virtualization tool useful for any organization struggling to gain operational and analytical insights from data dispersed and locked up in various business units, applications, and technology silos.  (Formerly known as JBoss Enterprise Data Services Platform).
buzz_tags:
  - datavirt
  - jboss datavirt
guides:
  Administration_and_Configuration_Guide:
    name: "Administration and Configuration"
  API_Documentation:
  Development_Guide_Volume_1_Client_Development:
    name: "Development Guide: Client Development"
  Development_Guide_Volume_2_Governance:
    name: "Development Guide: Governance"
  Development_Guide_Reference_Material:
    name: "Development Guide: Reference Material"
    formats:
      html:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6.2/html/Development_Guide_Volume_3_Reference_Material/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6.2/html-single/Development_Guide_Volume_3_Reference_Material/index.html
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6.2/pdf/Development_Guide_Volume_3_Reference_Material/Red_Hat_JBoss_Data_Virtualization-6.2-Development_Guide_Volume_3_Reference_Material-en-US.pdf
      epub:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6.2/epub/Development_Guide_Volume_3_Reference_Material/Red_Hat_JBoss_Data_Virtualization-6.2-Development_Guide_Volume_3_Reference_Material-en-US.epub
  Development_Guide_Server_Development:
    name: "Development Guide: Server Development"
    formats:
      html:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6.2/html/Development_Guide_Volume_4_Server_Development/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6.2/html-single/Development_Guide_Volume_4_Server_Development/index.html
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6.2/pdf/Development_Guide_Volume_4_Server_Development/Red_Hat_JBoss_Data_Virtualization-6.2-Development_Guide_Volume_4_Server_Development-en-US.pdf
      epub:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6.2/epub/Development_Guide_Volume_4_Server_Development/Red_Hat_JBoss_Data_Virtualization-6.2-Development_Guide_Volume_4_Server_Development-en-US.epub
  Development_Guide_Volume_5_Caching_Guide:
    name: "Development Guide: Caching Guide"
  Getting_Started_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/version-6.2/red-hat-jboss-data-virtualization-62-getting-started-guide/getting-started-guide
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/version-6.2/getting-started-guide
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.2-Getting_Started_Guide-en-US/Red_Hat_JBoss_Data_Virtualization-6.2-Getting_Started_Guide-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.2-Getting_Started_Guide-en-US/Red_Hat_JBoss_Data_Virtualization-6.2-Getting_Started_Guide-en-US.epub
  Installation_Guide:
  Migration_Guide:
  Release_Notes:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6.2/html/Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6.2/html-single/Release_Notes/index.html
      pdf:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6.2/pdf/Release_Notes/Red_Hat_JBoss_Data_Virtualization-6.2-Release_Notes-en-US.pdf
      epub:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Data_Virtualization/6.2/epub/Release_Notes/Red_Hat_JBoss_Data_Virtualization-6.2-Release_Notes-en-US.epub
  Security_Guide:
  User_Guide_Volume_1_Teiid_Designer:
  User_Guide_Volume_2_Modeshape_Tools:
description: 'An integration platform that unifies data from disparate sources into a single source and exposes the data as a reusable service.'
default_download_artifact_type: installer
downloads:
upstream_projects:
  - teiid
  - teiiddesigner
  - modeshape
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_datavirtualization.png
    url: /video/vimeo/76457404
    text: Launch into the virtual data world
evaluation: https://access.redhat.com/products/red-hat-jboss-data-virtualization/evaluation
