name: Red Hat Satellite
abbreviated_name: Satellite
current_version: 6.0.0.GA
product_category: it-infrastructure
customer_portal_download_url: https://access.redhat.com/downloads/content/250/
documentation_path: Red_Hat_Satellite
documentation_minor_version: 6.0
skip_installation_instructions: true
skip_maven_instructions: true
skip_quickstart_link: true
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKrVR8EiItdws_QVlsy7uprw
vimeo_album: https://vimeo.com/album/3555907
description: The easiest way to manage your Red Hat systems.
index:
  desc: |
    The easiest way to manage Red Hat® Enterprise Linux®, keeping your systems running efficiently, properly secured, and compliant with various standards.
guides:
  Release_Notes:
    formats:
      html:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Satellite/6.0/html/Release_Notes
      html-single:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Satellite/6.0/html-single/Release_Notes
      epub:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Satellite/6.0/epub/Release_Notes/Red_Hat_Satellite-6.0-Release_Notes-en-US.epub
      pdf:
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Satellite/6.0/pdf/Release_Notes/Red_Hat_Satellite-6.0-Release_Notes-en-US.pdf
  API_Guide:
  User_Guide:
  Transition_Guide:
  Technical_Notes:
  Provisioning_Guide:
  Installation_Guide:
skip_maven_instructions: true
other_product: true

