name: Red Hat JBoss Developer Studio
abbreviated_name: JBoss Developer Studio
product_logo: developer-studio.png
current_version: 9.0.0-CVE-2015-7501.GA
product_category: application-development
intro_video: https://vimeo.com/95444954
vimeo_album: http://vimeo.com/album/2982449
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKrxJ9OtX2Zmgw3nyeYs0QGR
buzz_tags: 
  - jbds
  - JBoss DevStudio
index:
  desc: |
    A certified, Eclipse-based integrated development environment (IDE) for developing, testing, and deploying rich web applications, mobile web apps, transactional enterprise apps, and service-oriented architecture (SOA)-based integration apps and services.
guides:
  Release_Notes:
  Install_Red_Hat_JBoss_Developer_Studio:
  Update_Red_Hat_JBoss_Developer_Studio:
default_download_artifact_type: jar_universal
description: 'A development environment with superior support for your entire development lifecycle.'
upstream_projects:
  - jbosstools
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_devstudio.png
    url: /video/vimeo/92554627
evaluation: https://access.redhat.com/products/red-hat-jboss-developer-studio/evaluation
