name: Red Hat Software Collections
abbreviated_name: Software Collections
product_logo: portal.png
current_version: 2.0.0.GA
documentation_path: Red_Hat_Software_Collections
product_category: it-infrastructure
customer_portal_download_url: https://access.redhat.com/downloads/content/69/ver=/rhel---7/7.1/x86_64/product-downloads
skip_installation_instructions: true
skip_maven_instructions: true
skip_quickstart_link: true
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKqiIGqG2f6WRu6xi_E223Gs
vimeo_album: https://vimeo.com/album/3555885
description: The latest development technologies for Red Hat Enterprise Linux
index:
  desc: |
    With a separate life cycle from Red Hat Enterprise Linux and a yearly release cadence, Red Hat Software Collections delivers the latest stable technologies such as: Python, PHP, Ruby, Node.js, MariaDB, MongoDB, PostgreSQL, Nginx, and much more.  
buzz_tags:
  - software collections
guides:
  Release_Notes:
    formats:
      html:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/html/2.0_Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/html-single/2.0_Release_Notes/index.html
      epub:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/epub/2.0_Release_Notes/Red_Hat_Software_Collections-2-2.0_Release_Notes-en-US.epub
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/pdf/2.0_Release_Notes/Red_Hat_Software_Collections-2-2.0_Release_Notes-en-US.pdf
  Installation_and_Usage: 
    formats:
      html: 
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/html/2.0_Release_Notes/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/html-single/2.0_Release_Notes/index.html  
  Packaging_Guide:
    formats:
      html:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/html/Packaging_Guide/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/html-single/Packaging_Guide/index.html
      epub:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/epub/Packaging_Guide/Red_Hat_Software_Collections-2-Packaging_Guide-en-US.epub
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Software_Collections/2/pdf/Packaging_Guide/Red_Hat_Software_Collections-2-Packaging_Guide-en-US.pdf
  Red_Hat_Enterprise_Linux_7_Developer_Guide:
    formats:
      html: 
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Developer_Guide/scl-utils.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Enterprise_Linux/7/html-single/Developer_Guide/index.html
      epub:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Enterprise_Linux/7/epub/Developer_Guide/Red_Hat_Enterprise_Linux-7-Developer_Guide-en-US.epub
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Enterprise_Linux/7/pdf/Developer_Guide/Red_Hat_Enterprise_Linux-7-Developer_Guide-en-US.pdf
  Red_Hat_Enterprise_Linux_7_Application_ABI_Compatilibity_Guide:
    formats:
      html: 
        url: https://access.redhat.com/articles/rhel-abi-compatibility        
  Red_Hat_Enterprise_Linux_6_Developer_Guide:
    formats:
      html: 
        url: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Developer_Guide/chap-RHSCL.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Enterprise_Linux/6/html-single/Developer_Guide/index.html
      epub:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Enterprise_Linux/6/epub/Developer_Guide/Red_Hat_Enterprise_Linux-6-Developer_Guide-en-US.epub
      pdf:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_Enterprise_Linux/6/pdf/Developer_Guide/Red_Hat_Enterprise_Linux-6-Developer_Guide-en-US.pdf
downloads:
skip_maven_instructions: true
other_product: true
get_started_multipath: true
get_started_paths:
  - id: "nodejs"
    name: Node.js
    default_file: get-started-rhel7-nodejs
  - id: "perl"
    name: Perl
    default_file: get-started-rhel7-perl
  - id: "php"
    name: PHP
    default_file: get-started-rhel7-php
  - id: "python"
    name: Python
    default_file: get-started-rhel7-python
  - id: "ruby"
    name: Ruby
    default_file: get-started-rhel7-ruby
