name: Red Hat JBoss Data Grid
abbreviated_name: JBoss Data Grid
product_logo: data-grid.png
current_version: 6.5.0.GA
product_category: application-development
intro_video: https://vimeo.com/95291413
vimeo_album: http://vimeo.com/album/2982379
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKqNQqGC2KitIx4eMsEVWBaQ
index:
  desc: |
    An in-memory data grid to accelerate application performance by offering fast, distributed data access, elastic scalability, and independence from the traditional data tier.
buzz_tags:
  - datagrid
  - jboss data grid
guides:
  Release_Notes:
  Administration_and_Configuration_Guide:
  API_Documentation:
    formats:
      html:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Grid/6.5/html/API_Documentation/index.html
      html-single:
        url: https://access.redhat.com/site/documentation/en-US/Red_Hat_JBoss_Data_Grid/6.5/html-single/API_Documentation/index.html  
  Developer_Guide:
  Getting_Started_Guide:
  Infinispan_Query_Guide:
default_download_artifact_type: zip
description: 'An intelligent, distributed caching solution that boosts application performance, provides greater deployment flexibility, and minimizes the overhead of standing up new applications.'
downloads:
upstream_projects:
  - infinispan
  - jgroups
  - hibernate_subprojects_search
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_datagrid.png
    url: /quickstarts/datagrid/helloworld-jdg
    text: Get started with Data Grid with this basic Infinispan example
evaluation: https://access.redhat.com/products/red-hat-jboss-data-grid/evaluation
skip_installation_instructions: true
skip_maven_instructions: true
