name: Red Hat Mobile Application Platform
abbreviated_name: Mobile Application Platform
current_version: 1.0.0.GA
product_category: application-development
intro_youtube: https://www.youtube.com/v=Dw-Z-R2C51U
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKroZy6oqmmS1uBXRbq8QiS9
vimeo_album: https://vimeo.com/album/3550548
skip_installation_instructions: true
skip_maven_instructions: true
skip_quickstart_link: true
description: Develop and deploy mobile apps in an agile and flexible manner with ease.
buzz_tags:
  - mobileplatform
  - mobile
index:
  desc: |
    Develop and deploy mobile apps in an agile and flexible manner.
guides:
downloads:
other_product: true
